apiVersion: v1
data:
  default-values.yaml: |
    replicaCount: 3
    service:
      type: ClusterIP
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sample-nginx-profile-bitnami-nginx-defaultvalues
  namespace: default
